<a href="https://colab.research.google.com/github/Sivagadiraju/Home_assignment4/blob/main/Scaled%20Dot-Product%20Attention%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from scipy.special import softmax

def scaled_dot_product_attention(Q, K, V):
    # Step 1: Dot product of Q and K^T
    scores = np.dot(Q, K.T)

    # Step 2: Scale the scores by sqrt(d), where d = dimension of key vectors
    d_k = K.shape[1]
    scaled_scores = scores / np.sqrt(d_k)

    # Step 3: Apply softmax to get attention weights
    attention_weights = softmax(scaled_scores, axis=1)

    # Step 4: Multiply attention weights with V
    output = np.dot(attention_weights, V)

    # Display results
    print("Attention Weights:\n", attention_weights)
    print("Output:\n", output)

# Test inputs
Q = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
K = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
V = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Run the function
scaled_dot_product_attention(Q, K, V)


Attention Weights:
 [[0.73105858 0.26894142]
 [0.26894142 0.73105858]]
Output:
 [[2.07576569 3.07576569 4.07576569 5.07576569]
 [3.92423431 4.92423431 5.92423431 6.92423431]]
